### ISSUE TITLE
amd-bundle creates incorrect code from kotlinJs amd code

### ISSUE THREAD

**Issue by NikkyAI** [TechQuery/AMD_bundle.js#1]
I am trying to use `amd-bundler` with kotlinJS
the project is configured to output `amd` javascript modules
i invoke it like so:

```
node_modules/.bin/amd-bundle -m build/kotlin-js/client-js/penta build/html/js/penta
```

`penta.js` is the entry point and all modules are in the same folder

the error i am encountering is that the generated code seems to be generating in the wrong order or maybe it skips things

```
penta.js:94 Uncaught ReferenceError: _ is not defined
    at _module_../penta.factory (penta.js:94)
    at include (penta.js:57)
    at penta.js:19712
    at penta.js:11
    at penta.js:13
_module_../penta.factory @ penta.js:94
include @ penta.js:57
(anonymous) @ penta.js:19712
(anonymous) @ penta.js:11
(anonymous) @ penta.js:13
```

seems to be this code (line 94)

```
    var $$importsForInline$$ =
        _.$$importsForInline$$ || (_.$$importsForInline$$ = {});
```

this code works when i just load it with require.js and main-data attribute
i attached the input files and the generated output as well here: [report.zip](https://github.com/TechQuery/AMD_bundle.js/files/3809436/report.zip)

the whole project is at https://github.com/NikkyAI/pentagame
to generate the js code you would run `./gradlew client-jsCopyJs`

**Comment by NikkyAI** [comment]
kotlinjs also has the dce task (dead code elimination) in prodution i would use the output of that, but i tried and the output fails in the same way

**Comment by TechQuery** [comment]
I'm so sorry for missing your issue from a bunch of notification messages.

This project has been without maintaining since early of the year which this issue submitted, then I became to use [Parcel][1] till now, it's the best bundler for most Web projects.

[1]: https://parceljs.org/
